services:
  # Web Service
  - type: web
    name: recruit-web
    env: node
    plan: free
    runtime: node
    buildCommand: "npm install"
    startCommand: "npm start"
    healthCheckPath: /
    rootDir: cv-server/blog
    nodeVersion: 20.20.0
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 3000
