services:
  # Web Service using Docker
  - type: web
    name: recruit-web
    env: docker
    plan: free
    healthCheckPath: /
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 3000
