const express = require('express');
const router = express.Router();
const { logoUpload } = require('../middlewares/logoUpload');
const businessDataMiddleware = require('../middlewares/businessDataMiddleware');
const userProfileController = require('../app/controllers/business/UserProfileController');
const detailApplicantController = require('../app/controllers/business/DetailApplicantController');
const profileViewsController = require('../app/controllers/business/ProfileViewsController');
const jobsController = require('../app/controllers/business/JobsController');
const jobDetailController = require('../app/controllers/business/JobDetailController');
const businessListController = require('../app/controllers/business/BusinessListController');
const applicantMatchingController = require('../app/controllers/business/ApplicantMatchingController');
const isBusinessOrApiKey = require('../middlewares/isBusinessOrApiKey');
router.use(businessDataMiddleware);
const { verifyToken, isBusiness } = require('../middlewares/verifyToken');
const registerController = require('../app/controllers/business/RegisterController');
const loginController = require('../app/controllers/business/LoginController');
const businessLoginController = require('../app/controllers/business/LoginController');
const jobCreateController = require('../app/controllers/business/JobCreateController');
const dashboardController = require('../app/controllers/business/DashboardController');
const profileController = require('../app/controllers/business/ProfileController');
const businessController = require('../app/controllers/business/BusinessController');
const SchelduleController = require('../app/controllers/job/SchelduleController');
const ActivityTracker = require('../middlewares/activityTracker');
const businessLayout = require('../middlewares/businessLayout');
router.use(businessLayout);


router.get('/', businessController.showBusinessList);
router.get('/profile', isBusiness, profileController.showProfile);
router.post('/profile/edit', isBusiness, profileController.updateProfile);
router.post('/job/create', isBusiness, jobCreateController.createJob);
router.post('/login', loginController.login);
router.get('/logout', businessLoginController.logout);
router.get('/register', registerController.showRegisterPage);
router.post('/register/submit', registerController.register);
router.post('/register-direct',logoUpload.single('logo'),registerController.register);
router.post('/upload-logo',isBusiness,logoUpload.single('logo'),profileController.uploadLogo);
router.post('/delete-logo', isBusiness, profileController.deleteLogo);
router.post('/delete-cv', isBusiness, profileController.deleteCV);
router.get('/test-matching', detailApplicantController.detail);
router.get('/applications', detailApplicantController.detail);
router.get('/jobs-list', verifyToken, businessController.jobList);
router.get('/jobs', isBusiness, businessController.jobList);
router.get('/dashboard', isBusiness, dashboardController.showDashboard);
router.get('/applicant/cv/:id', verifyToken, SchelduleController.viewApplicantCV);
router.get('/list', businessListController.showBusinessList);
router.get('/list-protected', verifyToken, businessController.showProtectedBusinessList);
router.get('/detail/:id', ActivityTracker.activityTracker, businessController.showBusinessDetail);
router.get('/detail-protected/:id', verifyToken, businessController.showProtectedBusinessDetail);
router.get('/jobs/matching', isBusiness, businessController.showMatchingPage);
router.get('/jobs/matching-simple/:jobId', isBusiness, businessController.showJobMatching);
router.get('/jobs/:id', businessController.showCompanyJobs);
router.post('/connect/:id', verifyToken, businessController.connectBusiness);
router.get('/job/create-page', isBusiness, businessController.showCreateJobPage);
router.get('/featured-company', verifyToken, businessController.showFeaturedCompany);
router.post('/schedule/meeting', businessController.scheduleMeeting);
router.get('/applications/stream', SchelduleController.handleApplicationStream.bind(SchelduleController));
router.get('/user-profile/:userId', userProfileController.viewUserProfile);
router.get('/cv/download/:cvId', userProfileController.downloadCV);
router.get('/cv/view/:cvId', userProfileController.viewApplicantCV);
router.get('/api/cv/:cvId', detailApplicantController.getCvData);
router.get('/api/cv-view/:cvId', detailApplicantController.viewCvDirect);   
router.get('/applicants/:id', detailApplicantController.viewApplicant);
router.get('/profile-views', profileViewsController.viewProfileViews);
router.get('/jobs', jobsController.viewJobs);
router.get('/api/job/:id', jobDetailController.getJobDetailApi);
router.get('/job/:id', jobDetailController.viewJobDetail);
router.get('/api/job/:jobId/matching-applicants', isBusinessOrApiKey, applicantMatchingController.getMatchingApplicants);
router.get('/api/matching-applicants/all', isBusinessOrApiKey, applicantMatchingController.getAllJobsApplicantRecommendations);
router.get('/api/applicant/:userId/profile', applicantMatchingController.getApplicantProfile);
router.get('/api/applicant/:userId/:jobId/analysis', applicantMatchingController.getDetailedMatchingAnalysis);
router.get('/api/jobs', applicantMatchingController.getBusinessJobs);
router.post('/api/matching-preferences', isBusinessOrApiKey, applicantMatchingController.updateMatchingPreferences);
router.put('/:id/update', detailApplicantController.updateApplicationStatus);
router.delete('/jobApplied/:id', detailApplicantController.deleteApplication);


module.exports = router;
